version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: cesma/app
        restart: unless-stopped
        ports:
            - "8001:80"
        networks:
            - cesma-net
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'db-data:/var/lib/mysql'
        networks:
            - cesma-net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - cesma-net
    #     depends_on:
    #         - mysql-external
    #         - mysql

networks:
    cesma-net:
        driver: bridge

volumes:
    db-data:
        driver: local